# Site settings
title: Antonia Chain
email: antoniachainuk@gmail.com
description: Crime Writer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.antoniachain.com" # the base hostname & protocol for your site
twitter_username: AntoniaChain
facebook_url: https://www.facebook.com/antoniachain
twitter_url: http://twitter.com/antoniachain
excerpt_separator: "\n---\n"
permalink: /:year/:title.html

# Build settings
markdown: kramdown
