---
title: Antonia Chain
timezone: Europe/London
collections:
  podcast:
    title: Podcast
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work-in-progress:
    title: Work in Progress
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: post
tagline: Crime Writer
description: Crime Writer
facebook_url: https://www.facebook.com/antoniachain
twitter_url: http://twitter.com/antoniachain
twitter_username: antoniachain
itunes_url: https://itunes.apple.com/gb/podcast/shadow-of-the-wing/id1099255231
soundcloud_url: https://soundcloud.com/shadowofthewing
email: antoniachainuk@gmail.com
url: http://www.antoniachain.com
baseurl: 
permalink: "/:year/:title.html"
paginate: 5
markdown: kramdown
plugins:
- jekyll-paginate
