---
title: Antonia Chain
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: post
tagline: Crime Writer
description: Crime Writer
facebook_url: https://www.facebook.com/antoniachain
twitter_url: http://twitter.com/antoniachain
twitter_username: antoniachain
itunes_url: https://itunes.apple.com/gb/podcast/shadow-of-the-wing/id1099255231
soundcloud_url: https://soundcloud.com/shadowofthewing
email: antoniachainuk@gmail.com
google_analytics_id: UA-75846413-1
url: http://www.antoniachain.com
baseurl: 
permalink: "/:year/:title.html"
paginate: 5
markdown: kramdown
gems:
- jekyll-paginate
